/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.ai.edge.gallery.data.brainbox

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single knowledge node (neuron) in the CLU/BOX GraphRAG memory system.
 *
 * @param id         Unique identifier for this node (e.g. a UUID).
 * @param label      Human-readable name for the node (maps to "title" in the AI tool interface).
 * @param type       Category or type of the node (e.g. "Concept", "Code", "Session_Log", "Lore").
 * @param content    The raw text content stored at this node — the ground truth (markdown / code).
 * @param synapses   Comma-separated [[Wiki-Links]] referencing other Neuron labels.
 *                   Example: "[[M-CLU_Architecture_v1]],[[Icarus_Base_Design]]"
 * @param isCore     When `true` the neuron is a **Core Memory** — protected from bulk deletion
 *                   and auto-compression. Default is `false` (Malleable).
 * @param falsePaths Comma-separated list of incorrect assumptions or dead-end paths
 *                   the AI has encountered for this topic. Helps avoid repeating mistakes.
 * @param embedding  Vector embedding of the concatenated text (label + content + synapses),
 *                   generated by the VectorEngine. Used for cosine-similarity semantic search.
 */
@Entity(tableName = "neurons")
data class NeuronEntity(
  @PrimaryKey val id: String,
  val label: String,
  val type: String,
  val content: String,
  val synapses: String = "",
  /** When `true` the neuron is a Core Memory and is protected from bulk deletion / compression. */
  val isCore: Boolean = false,
  /** Incorrect assumptions / dead-end paths related to this neuron's topic. */
  val falsePaths: String = "",
  /** Vector embedding for semantic similarity search. */
  val embedding: FloatArray = floatArrayOf(),
) {
  // FloatArray does not have structural equality by default, so override equals/hashCode.
  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (other !is NeuronEntity) return false
    return id == other.id &&
      label == other.label &&
      type == other.type &&
      content == other.content &&
      synapses == other.synapses &&
      isCore == other.isCore &&
      falsePaths == other.falsePaths &&
      embedding.contentEquals(other.embedding)
  }

  override fun hashCode(): Int {
    var result = id.hashCode()
    result = 31 * result + label.hashCode()
    result = 31 * result + type.hashCode()
    result = 31 * result + content.hashCode()
    result = 31 * result + synapses.hashCode()
    result = 31 * result + isCore.hashCode()
    result = 31 * result + falsePaths.hashCode()
    result = 31 * result + embedding.contentHashCode()
    return result
  }
}
